
// --- Stats Animation ---
async function fetchGitHubStats() {
    const countElement = document.getElementById('project-count');
    if (!countElement) return;

    try {
        const username = 'Nandan0402';
        const response = await fetch(`https://api.github.com/users/${username}`);

        if (!response.ok) throw new Error('Failed to fetch user data');

        const data = await response.json();
        const publicRepos = data.public_repos;
        const githubFollowers = data.followers;

        // Manual Counts
        const docustoreInsta = 150;
        const docustoreLinkedIn = 50;
        const nandanLinkedIn = 200;
        const totalLinkedIn = docustoreLinkedIn + nandanLinkedIn;

        // Animate Independent Stats
        animateValue("project-count", publicRepos);
        animateValue("follower-count", githubFollowers);
        animateValue("insta-count", docustoreInsta);
        animateValue("linkedin-count", totalLinkedIn);

    } catch (error) {
        console.error("Error fetching stats:", error);
        document.getElementById('project-count').innerText = "10";
        if (document.getElementById('follower-count')) document.getElementById('follower-count').innerText = "500";
    }
}

function animateValue(id, endValue) {
    const element = document.getElementById(id);
    if (!element) return;

    let current = 0;
    const increment = Math.ceil(endValue / 50) || 1;
    const timer = setInterval(() => {
        current += increment;
        if (current >= endValue) {
            current = endValue;
            clearInterval(timer);
            element.innerHTML = `${current}`;
        } else {
            element.innerText = current;
        }
    }, 40);
}



// --- GitHub API Integration ---
async function fetchGitHubProjects() {
    const container = document.getElementById('github-projects');
    if (!container) return; // Not on projects page

    const username = 'Nandan0402';

    try {
        // Fetch ALL repos (up to 100 per page)
        const response = await fetch(`https://api.github.com/users/${username}/repos?sort=updated&per_page=100`);
        if (!response.ok) throw new Error('Failed to fetch repositories');

        const repos = await response.json();
        renderProjects(repos);

    } catch (error) {
        console.error("Error fetching projects:", error);
        container.innerHTML = `<p style="color:red;">Failed to load projects from GitHub. <br> Check console for details.</p>`;
    }
}

function renderProjects(repos) {
    const container = document.getElementById('github-projects');
    container.innerHTML = ''; // Clear loading text

    repos.forEach(repo => {
        // Create Card
        const card = document.createElement('div');
        card.className = 'project-card';
        card.setAttribute('data-tilt', ''); // Add Tilt effect

        // OpenGraph Image (Auto-generated by GitHub)
        const imageUrl = `https://opengraph.githubassets.com/1/${repo.full_name}`;

        card.innerHTML = `
            <img src="${imageUrl}" alt="${repo.name} Preview">
            <div class="p-content">
                <h3>${repo.name}</h3>
                <p>${repo.description || 'No description available.'}</p>
                <div class="tags">
                    <span>⭐ ${repo.stargazers_count}</span>
                    <span>${repo.language || 'Code'}</span>
                </div>
                <a href="${repo.html_url}" target="_blank">View Project</a>
            </div>
        `;

        container.appendChild(card);
    });

    // Re-init Tilt for new elements
    if (typeof VanillaTilt !== 'undefined') {
        VanillaTilt.init(document.querySelectorAll(".project-card"), {
            max: 15,
            speed: 400,
            glare: true,
            "max-glare": 0.2
        });
    }
}

// --- Initialize ---
document.addEventListener('DOMContentLoaded', () => {
    fetchGitHubStats();     // For Home Page
    fetchGitHubProjects();  // For Projects Page
});
